version: '3.1'
services:
  Service:
    build: ./general
    image: general_image
    container_name: general_container
    ports:
      - "8080:8080"
    depends_on:
      - currency-db
    environment:
      - DB_HOST=currency-db
      - DB_PORT=5432
      - DB_NAME=currency
      - POSTGRES_USER=admin_currency
      - POSTGRES_PASSWORD=admin_currency
    restart: on-failure

  currency-db:
    image: postgres:14-alpine
    container_name: currency_db_container
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6542:5432"
    environment:
      - DB_NAME=currency
      - POSTGRES_USER=admin_currency
      - POSTGRES_PASSWORD=admin_currency
    restart: on-failure